#!/usr/bin/python
import rospy
from naoqi_driver.naoqi_node import NaoqiNode
from pepper_sociale_pkg.srv import Say

class AnimatedSay(NaoqiNode):
    """
    Questa classe fornisce un proxy verso AlAnimatedSpeech che utilizza le API di NAOqi
    per permettere al robot di parlare. Inoltre fornisce un Service per dare la possibilita all utente finale
    di utilizzare tali API.
    """
    def __init__(self):
        """
        Inizializza il nodo animated_speech
        """
        NaoqiNode.__init__(self,'animated_speech')
        #set pepper ip
        self.pip="10.0.1.230"
        self.connectNaoQi()    
        pass

    def say(self,data):
        """
        Utilizza il metodo say dell'oggetto proxy ALAnimatedSpeech
        """
        rospy.loginfo("SPEECH SERVICE CALL: %s" % data.message)
        self.speech.say(data.message)
        return True
        
    def connectNaoQi(self):
        """
        Istanzia il proxy verso le API di NAOqi e mette a disposizione un servizio per utilizzarle.
        """
        self.speech=self.get_proxy("ALAnimatedSpeech")
        self.s = rospy.Service('animated_say', Say, self.say)

if __name__=="__main__":
    pub = AnimatedSay()
    rospy.spin()